### ISSUE TITLE
string concatenation in lang string file doesn't work :-(

### ISSUE THREAD

**Issue by danmarsden** [ethz-let/quiz-report_filedownloader#1]
https://github.com/ethz-let/quiz-report_filedownloader/blob/master/lang/en/quiz_filedownloader.php#L57

string concatentaion in the lang packs is not allowed - it causes problems for the Moodle translation tool

eg:
$string['test'] = "sometext"."somemoretext";
or
$string['test'] = "sometext".$string['someotheritem'];

each string must be contained within one set of quotes eg:
$string['test'] = "sometext somemoretext";

**Comment by nexterday** [comment]
Hi Dan, thanks for bringing it to our attention. I suppose this has -in a way or another- being autofixes by codechecker and gone unnoticed. I concatenated them now as an emergency fix and will update the language author so they format it right.

**Comment by danmarsden** [comment]
haha - that was quick! :-) - I think that might be the only blocker for approval so if you drop that as a new version into the plugins db I might be able to publish it today! :-)

**Comment by danmarsden** [comment]
oh - you might want to do the other lang pack as well while you're there:
https://github.com/ethz-let/quiz-report_filedownloader/blob/master/lang/de/quiz_filedownloader.php#L57

not sure if it's a blocker though as en is the master lang pack and I think amos only gets that on publish.
