### ISSUE TITLE
docx file suffix gets changed to zip

### ISSUE THREAD

**Issue by DavidPruem** [ethz-let/quiz-report_filedownloader#3]
I just tested this plugin and found that Word Files (.docx) that got downloaded were renamed to .zip. I could easily rename them back to .docx, but it would be better to prevent this behavior.

**Comment by nexterday** [comment]
Could you please screenshot the directory after extracting the downloaded zip and its sub directories where you see that files are actually zipped?

No files are zipped or manipulated (apart from file name cleaning)

**Comment by jppellet** [comment]
I had the same problem. Some Excel and Word files were showing up as zip files that I had to rename. Quite weird. I can't post an actual screenshot here containing students names, but it looked roughly like this:

<img width="345" alt="image" src="https://github.com/user-attachments/assets/c4fe7b74-4719-4f58-9827-3d0a5cf62c6d">

Funny that this is not systematic — you can see another Excel file whose name wasn't changed. Maybe it has to do with filenames being too long or containing some nonstandard characters…
